#ifndef SFU_UTIL_METRIC_LIST_H
#define SFU_UTIL_METRIC_LIST_H

/* Single source of truth for metric IDs, names, and snapshot order. */
#define SFU_METRIC_LIST(X) \
  X(MSG_TRUNC_DROP, "msg_trunc_drop") \
  X(JSON_REJECT, "json_reject") \
  X(RTCP_COMPOUND_MALFORMED, "rtcp_compound_malformed") \
  X(RTCP_MEMBER_UNKNOWN, "rtcp_member_unknown") \
  X(RTCP_TWCC_BAD, "rtcp_twcc_bad") \
  X(RTCP_NACK_BAD, "rtcp_nack_bad") \
  X(RTCP_PLI_BAD, "rtcp_pli_bad") \
  X(RTCP_FIR_BAD, "rtcp_fir_bad") \
  X(RTCP_FIR_RECEIVED, "rtcp_fir_received") \
  X(RTCP_NACK_DROPPED, "rtcp_nack_dropped") \
  X(RTX_BUILD_FAIL, "rtx_build_fail") \
  X(RTX_SEQ_TRANSLATE_FAIL, "rtx_seq_translate_fail") \
  X(RTX_PROTECT_FAIL, "rtx_protect_fail") \
  X(RTX_PROTECT_REPLAY_OLD, "rtx_protect_replay_old") \
  X(RTX_PROTECT_REPLAY_FAIL, "rtx_protect_replay_fail") \
  X(RTCP_KF_UNRESOLVED, "rtcp_kf_unresolved") \
  X(REMB_SENT, "remb_sent") \
  X(REMB_CONTRIBUTION_WRITTEN, "remb_contribution_written") \
  X(REMB_CONTRIBUTION_STALE, "remb_contribution_stale") \
  X(REMB_AGGREGATE_EMPTY, "remb_aggregate_empty") \
  X(REMB_AGGREGATE_NO_FRESH, "remb_aggregate_no_fresh") \
  X(REMB_AGGREGATE_TARGET_CHANGED, "remb_aggregate_target_changed") \
  X(REMB_AGGREGATE_THROTTLED, "remb_aggregate_throttled") \
  X(REMB_AGGREGATE_SENT, "remb_aggregate_sent") \
  X(REMB_SEND_REJECTED, "remb_send_rejected") \
  X(REMB_NO_MEDIA_SSRC, "remb_no_media_ssrc") \
  X(REMB_PROTECT_FAIL, "remb_protect_fail") \
  X(REMB_PACKET_ALLOC_FAIL, "remb_packet_alloc_fail") \
  X(REMB_CAMERA_SENT, "remb_camera_sent") \
  X(REMB_SCREEN_SENT, "remb_screen_sent") \
  X(REMB_CAMERA_THROTTLED, "remb_camera_throttled") \
  X(REMB_SCREEN_THROTTLED, "remb_screen_throttled") \
  X(REMB_CAMERA_REJECTED, "remb_camera_rejected") \
  X(REMB_SCREEN_REJECTED, "remb_screen_rejected") \
  X(CONGESTION_DIAG_LOG, "congestion_diag_log") \
  X(BANDWIDTH_ALLOCATOR_RUNS, "bandwidth_allocator_runs") \
  X(BANDWIDTH_ALLOCATOR_ACTIVE_STREAMS, "bandwidth_allocator_active_streams") \
  X(BANDWIDTH_ALLOCATOR_UNALLOCATED_BPS, "bandwidth_allocator_unallocated_bps") \
  X(BANDWIDTH_SCREEN_PREFERRED, "bandwidth_screen_preferred") \
  X(BANDWIDTH_SCREEN_BELOW_PREFERRED, "bandwidth_screen_below_preferred") \
  X(BANDWIDTH_CAMERA_DEFERRED_FOR_SCREEN, "bandwidth_camera_deferred_for_screen") \
  X(CONGESTION_TWCC_FEEDBACK, "congestion_twcc_feedback") \
  X(CONGESTION_TWCC_LOST, "congestion_twcc_lost") \
  X(CONGESTION_NACK_REQUESTED, "congestion_nack_requested") \
  X(CONGESTION_RTX_CACHE_HIT, "congestion_rtx_cache_hit") \
  X(CONGESTION_RTX_CACHE_MISS, "congestion_rtx_cache_miss") \
  X(CONGESTION_RTX_SENT, "congestion_rtx_sent") \
  X(CONGESTION_PLI_RECEIVED, "congestion_pli_received") \
  X(CONGESTION_PLI_SENT, "congestion_pli_sent") \
  X(CONGESTION_PLI_COALESCED, "congestion_pli_coalesced") \
  X(TWCC_WRITE_FAIL, "twcc_write_fail") \
  X(EGRESS_PROTECT_FAIL, "egress_protect_fail") \
  X(EGRESS_PROTECT_REPLAY_OLD, "egress_protect_replay_old") \
  X(EGRESS_PROTECT_REPLAY_FAIL, "egress_protect_replay_fail") \
  X(EGRESS_PROTECT_FAIL_AUDIO, "egress_protect_fail_audio") \
  X(EGRESS_PROTECT_FAIL_VIDEO, "egress_protect_fail_video") \
  X(EGRESS_SEQ_TRANSLATE_FAIL, "egress_seq_translate_fail") \
  X(EGRESS_SEQ_TRANSLATE_TABLE_FULL, "egress_seq_translate_table_full") \
  X(DTLS_RESTART_DETECTED, "dtls_restart_detected") \
  X(DTLS_RESTART_ESTABLISHED, "dtls_restart_established") \
  X(DTLS_RESTART_FAILED, "dtls_restart_failed") \
  X(DTLS_RESTART_TIMEOUT, "dtls_restart_timeout") \
  X(DTLS_RESTART_DUPLICATE, "dtls_restart_duplicate") \
  X(INGRESS_UNPROTECT_FAIL_RTP, "ingress_unprotect_fail_rtp") \
  X(INGRESS_UNPROTECT_FAIL_RTCP, "ingress_unprotect_fail_rtcp") \
  X(INGRESS_UNPROTECT_AUTH_FAIL, "ingress_unprotect_auth_fail") \
  X(INGRESS_UNPROTECT_REPLAY_FAIL, "ingress_unprotect_replay_fail") \
  X(INGRESS_UNPROTECT_REPLAY_OLD, "ingress_unprotect_replay_old") \
  X(INGRESS_UNPROTECT_NO_CTX, "ingress_unprotect_no_ctx") \
  X(INGRESS_UNPROTECT_OTHER, "ingress_unprotect_other") \
  X(INGRESS_UNPROTECT_PREVIOUS_GENERATION, "ingress_unprotect_previous_generation") \
  X(EGRESS_SEND_FULL, "egress_send_full") \
  X(PACER_DROPPED_ENH, "pacer_dropped_enh") \
  X(PACER_DROPPED_ENH_FRAMES, "pacer_dropped_enh_frames") \
  X(VP9_ENH_ORPHAN_CONTINUATION, "vp9_enh_orphan_continuation") \
  X(RTX_DROPPED_BUDGET, "rtx_dropped_budget") \
  X(AUDIENCE_RTP_DROP, "audience_rtp_drop") \
  X(RTP_PARSE_FAIL, "rtp_parse_fail") \
  X(MUTED_AUDIO_DROP, "muted_audio_drop") \
  X(UNNEGOTIATED_RTP_DROP, "unnegotiated_rtp_drop") \
  X(VP9_DESCRIPTOR_PARSE_FAIL, "vp9_descriptor_parse_fail") \
  X(PACKET_POOL_EXHAUSTED, "packet_pool_exhausted") \
  X(PACKET_META_POOL_EXHAUSTED, "packet_meta_pool_exhausted") \
  X(WORKER_INBOX_FULL, "worker_inbox_full") \
  X(FANOUT_RING_FULL, "fanout_ring_full") \
  X(FANOUT_JOB_POOL_EXHAUSTED, "fanout_job_pool_exhausted") \
  X(RELEASE_QUEUE_FULL, "release_queue_full") \
  X(SEND_SQ_FULL, "send_sq_full") \
  X(EGRESS_ADMISSION_DROP, "egress_admission_drop") \
  X(EGRESS_MID_NOT_NEGOTIATED, "egress_mid_not_negotiated") \
  X(EGRESS_OUTPUT_ALLOC, "egress_output_alloc") \
  X(EGRESS_COPIED_BYTES, "egress_copied_bytes") \
  X(FANOUT_BATCH_JOBS, "fanout_batch_jobs") \
  X(FANOUT_BATCH_TARGETS, "fanout_batch_targets") \
  X(PACED_SEND_ENQUEUED, "paced_send_enqueued") \
  X(PACED_SEND_SENT, "paced_send_sent") \
  X(PACED_SEND_FULL_DROP, "paced_send_full_drop") \
  X(PACED_SEND_ENQUEUE_DROP, "paced_send_enqueue_drop") \
  X(PACED_SEND_SQ_FULL, "paced_send_sq_full") \
  X(PACED_SEND_DELAY_FRAME_DROP, "paced_send_delay_frame_drop") \
  X(PACED_SEND_FRAME_PACKET_DROP, "paced_send_frame_packet_drop") \
  X(PACED_SEND_INCOMPLETE_FRAME_DROP, "paced_send_incomplete_frame_drop") \
  X(PACED_SEND_INCOMPLETE_FRAME_INVALIDATE, "paced_send_incomplete_frame_invalidate") \
  X(PACED_SEND_DELAY_CROSSING, "paced_send_delay_crossing") \
  X(PACED_SEND_SCREEN_BACKLOG_DROP, "paced_send_screen_backlog_drop") \
  X(PACED_SEND_BACKLOG_DROP_FRAMES, "paced_send_backlog_drop_frames") \
  X(PACED_SEND_RATE_FLOOR, "paced_send_rate_floor") \
  X(PACED_SEND_DRAIN_CAP_HIT, "paced_send_drain_cap_hit") \
  X(PACED_SEND_RELEASE_LATE, "paced_send_release_late") \
  X(PACED_SEND_INPUT_FRAME_SLOW, "paced_send_input_frame_slow") \
  X(DISPATCH_NULL_PAYLOAD, "dispatch_null_payload") \
  X(AF_XDP_INVALID_RX_FRAME, "af_xdp_invalid_rx_frame") \
  X(AF_XDP_INVALID_RX_RETURN, "af_xdp_invalid_rx_return") \
  X(AF_XDP_NEIGHBOR_MISS, "af_xdp_neighbor_miss") \
  X(AF_XDP_TX_KERNEL_FALLBACK, "af_xdp_tx_kernel_fallback") \
  X(AF_XDP_TX_KERNEL_FALLBACK_BACKPRESSURE, "af_xdp_tx_kernel_fallback_backpressure") \
  X(AF_XDP_TX_KERNEL_FALLBACK_ERROR, "af_xdp_tx_kernel_fallback_error") \
  X(AF_XDP_INVALID_TX_COMPLETION, "af_xdp_invalid_tx_completion") \
  X(AF_XDP_TX_FRAME_STARVATION, "af_xdp_tx_frame_starvation") \
  X(AF_XDP_TX_KERNEL_FALLBACK_COMPLETED, "af_xdp_tx_kernel_fallback_completed") \
  X(AF_XDP_TX_PERMANENT_FAILURE, "af_xdp_tx_permanent_failure") \
  X(AF_XDP_TX_RING_BACKPRESSURE, "af_xdp_tx_ring_backpressure") \
  X(AF_XDP_TX_CANCELED_SHUTDOWN, "af_xdp_tx_canceled_shutdown") \
  X(SEND_CONTROL_ACCEPTED, "send_control_accepted") \
  X(SEND_CONTROL_QUEUE_FULL, "send_control_queue_full") \
  X(SEND_NORMAL_QUEUE_FULL, "send_normal_queue_full") \
  X(SEND_CONTROL_DISPATCHED, "send_control_dispatched") \
  X(SEND_NORMAL_DISPATCHED, "send_normal_dispatched") \
  X(SEND_CONTROL_BYPASS, "send_control_bypass") \
  X(SEND_FAIRNESS_NORMAL, "send_fairness_normal") \
  X(SEND_CONTROL_CANCELED, "send_control_canceled") \
  X(SEND_NORMAL_CANCELED, "send_normal_canceled") \
  X(IO_URING_PENDING_FULL, "io_uring_pending_full") \
  X(IO_URING_SEND_QUEUED, "io_uring_send_queued") \
  X(AF_XDP_PENDING_FULL, "af_xdp_pending_full") \
  X(AF_XDP_SEND_QUEUED, "af_xdp_send_queued") \
  X(CAMERA_DISABLED_RTP_DROP, "camera_disabled_rtp_drop") \
  X(SCREEN_DISABLED_RTP_DROP, "screen_disabled_rtp_drop") \
  X(INGRESS_ROC_RECOVERED, "ingress_roc_recovered") \
  X(MID_WRITE_FAIL, "mid_write_fail") \
  X(PTT_INACTIVE_AUDIO_DROP, "ptt_inactive_audio_drop") \
  X(ROUTER_ASSIGNMENT_PENDING, "router_assignment_pending") \
  X(CONGESTION_RTX_QUEUED, "congestion_rtx_queued") \
  X(CONGESTION_RTX_BYTES, "congestion_rtx_bytes") \
  X(CONGESTION_RTX_FULL_DROP, "congestion_rtx_full_drop") \
  X(CONGESTION_RTX_EXPIRED_DROP, "congestion_rtx_expired_drop") \
  X(CONGESTION_RTX_STALE_DROP, "congestion_rtx_stale_drop") \
  X(CONGESTION_PROBE_STARTED, "congestion_probe_started") \
  X(CONGESTION_PROBE_SUCCEEDED, "congestion_probe_succeeded") \
  X(CONGESTION_PROBE_FAILED, "congestion_probe_failed") \
  X(CONGESTION_PROBE_ABORTED, "congestion_probe_aborted") \
  X(CONGESTION_PROBE_QUEUED, "congestion_probe_queued") \
  X(CONGESTION_PROBE_SENT, "congestion_probe_sent") \
  X(CONGESTION_PROBE_BYTES, "congestion_probe_bytes") \
  X(CONGESTION_PROBE_FULL_DROP, "congestion_probe_full_drop") \
  X(CONGESTION_PROBE_EXPIRED_DROP, "congestion_probe_expired_drop") \
  X(CONGESTION_PROBE_STALE_DROP, "congestion_probe_stale_drop")

#endif /* SFU_UTIL_METRIC_LIST_H */
